# src/rhosocial/activerecord/backend/impl/firebird/protocols.py
"""Firebird dialect-specific protocol definitions."""

from typing import Any, Dict, List, Optional, Protocol, Tuple, runtime_checkable


@runtime_checkable
class FirebirdDMLOperationSupport(Protocol):
    def supports_update_or_insert(self) -> bool: ...
    def supports_returning(self) -> bool: ...
    def supports_merge(self) -> bool: ...
    def supports_execute_block(self) -> bool: ...
    def format_update_or_insert(self, expr: Any) -> Tuple[str, tuple]: ...
    def format_execute_block(self, expr: Any) -> Tuple[str, tuple]: ...


@runtime_checkable
class FirebirdGeneratorSupport(Protocol):
    def supports_create_sequence(self) -> bool: ...
    def supports_create_generator(self) -> bool: ...
    def supports_alter_sequence(self) -> bool: ...
    def format_gen_id(self, generator_name: str, step: int = 1) -> Tuple[str, tuple]: ...
    def format_next_value_for(self, sequence_name: str) -> Tuple[str, tuple]: ...


@runtime_checkable
class FirebirdBlobSupport(Protocol):
    def supports_blob(self) -> bool: ...
    def supports_blob_sub_type(self, sub_type: int) -> bool: ...
    def format_blob_literal(self, value: bytes, sub_type: int = 0) -> Tuple[str, tuple]: ...


@runtime_checkable
class FirebirdLockingSupport(Protocol):
    def supports_for_update_with_lock(self) -> bool: ...
    def supports_skip_locked(self) -> bool: ...


@runtime_checkable
class FirebirdTransactionSupport(Protocol):
    def supports_snapshot_isolation(self) -> bool: ...
    def supports_table_stability(self) -> bool: ...
    def supports_wait_option(self) -> bool: ...
    def supports_lock_timeout(self) -> bool: ...


@runtime_checkable
class FirebirdTableSupport(Protocol):
    def supports_computed_by(self) -> bool: ...
    def supports_generated_always(self) -> bool: ...
    def supports_identity_columns(self) -> bool: ...
    def supports_external_file(self) -> bool: ...


@runtime_checkable
class FirebirdTriggerSupport(Protocol):
    def supports_trigger_position(self) -> bool: ...


@runtime_checkable
class FirebirdReturningSupport(Protocol):
    def supports_returning_into(self) -> bool: ...


@runtime_checkable
class FirebirdIntrospectionSupport(Protocol):
    def supports_mon_tables(self) -> bool: ...


@runtime_checkable
class FirebirdExecuteBlockSupport(Protocol):
    def supports_execute_block(self) -> bool: ...
    def format_execute_block(self, block: Any) -> Tuple[str, tuple]: ...


@runtime_checkable
class FirebirdExplainSupport(Protocol):
    def supports_explain_plan(self) -> bool: ...


@runtime_checkable
class FirebirdFunctionSupport(Protocol):
    def supports_list_function(self) -> bool: ...
    def supports_replace_function(self) -> bool: ...
    def supports_position_function(self) -> bool: ...
    def supports_char_length_function(self) -> bool: ...
    def supports_bit_functions(self) -> bool: ...
    def supports_date_time_functions(self) -> bool: ...
    def supports_string_functions(self) -> bool: ...
    def supports_gen_uid(self) -> bool: ...


@runtime_checkable
class FirebirdBooleanSupport(Protocol):
    def supports_boolean_type(self) -> bool: ...


@runtime_checkable
class FirebirdDecFloatSupport(Protocol):
    def supports_decfloat(self) -> bool: ...


@runtime_checkable
class FirebirdPaginationSupport(Protocol):
    def supports_rows_syntax(self) -> bool: ...
    def supports_offset_fetch(self) -> bool: ...


@runtime_checkable
class FirebirdDatabaseTriggerSupport(Protocol):
    def supports_database_triggers(self) -> bool: ...


@runtime_checkable
class FirebirdWindowFunctionSupport(Protocol):
    def supports_window_functions(self) -> bool: ...


@runtime_checkable
class FirebirdCTESupport(Protocol):
    def supports_cte(self) -> bool: ...
    def supports_recursive_cte(self) -> bool: ...


@runtime_checkable
class FirebirdFullTextSearchSupport(Protocol):
    def supports_fulltext_index(self) -> bool: ...


@runtime_checkable
class FirebirdUDFSupport(Protocol):
    def supports_udf(self) -> bool: ...
    def supports_declare_external_function(self) -> bool: ...


@runtime_checkable
class FirebirdPackageSupport(Protocol):
    def supports_packages(self) -> bool: ...
    def supports_create_package(self) -> bool: ...
    def supports_create_package_body(self) -> bool: ...


@runtime_checkable
class FirebirdGlobalMappingSupport(Protocol):
    def supports_global_temporary_table(self) -> bool: ...
    def supports_on_commit_delete_rows(self) -> bool: ...
    def supports_on_commit_preserve_rows(self) -> bool: ...


@runtime_checkable
class FirebirdMonitoringSupport(Protocol):
    def supports_monitoring(self) -> bool: ...


@runtime_checkable
class FirebirdRoleSupport(Protocol):
    def supports_roles(self) -> bool: ...
    def supports_create_role(self) -> bool: ...
    def supports_autonomous_transaction(self) -> bool: ...


@runtime_checkable
class FirebirdCursorSupport(Protocol):
    def supports_for_cursor(self) -> bool: ...
    def supports_as_cursor(self) -> bool: ...


@runtime_checkable
class FirebirdCollationSupport(Protocol):
    def supports_collation(self) -> bool: ...
    def supports_character_set(self) -> bool: ...


@runtime_checkable
class FirebirdExceptionSupport(Protocol):
    def supports_exception(self) -> bool: ...
    def supports_create_exception(self) -> bool: ...


@runtime_checkable
class FirebirdContextVariableSupport(Protocol):
    def supports_context_variables(self) -> bool: ...


__all__ = [
    "FirebirdDMLOperationSupport",
    "FirebirdGeneratorSupport",
    "FirebirdBlobSupport",
    "FirebirdLockingSupport",
    "FirebirdTransactionSupport",
    "FirebirdTableSupport",
    "FirebirdTriggerSupport",
    "FirebirdReturningSupport",
    "FirebirdIntrospectionSupport",
    "FirebirdExecuteBlockSupport",
    "FirebirdExplainSupport",
    "FirebirdFunctionSupport",
    "FirebirdBooleanSupport",
    "FirebirdDecFloatSupport",
    "FirebirdPaginationSupport",
    "FirebirdDatabaseTriggerSupport",
    "FirebirdWindowFunctionSupport",
    "FirebirdCTESupport",
    "FirebirdFullTextSearchSupport",
    "FirebirdUDFSupport",
    "FirebirdPackageSupport",
    "FirebirdGlobalMappingSupport",
    "FirebirdMonitoringSupport",
    "FirebirdRoleSupport",
    "FirebirdCursorSupport",
    "FirebirdCollationSupport",
    "FirebirdExceptionSupport",
    "FirebirdContextVariableSupport",
]