CREATE TABLE event_tests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'draft',
    revision INT DEFAULT 1,
    content BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
