CREATE TABLE event_tracking_models (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content BLOB SUB_TYPE TEXT NOT NULL,
    view_count INT DEFAULT 0,
    last_viewed_at TIMESTAMP
)
