import os
from dataclasses import replace

import pytest
from rhosocial.activerecord.backend.impl.firebird import (
    FirebirdBackend,
    FirebirdConnectionConfig,
)


def _apply_pooled_database(config: FirebirdConnectionConfig) -> FirebirdConnectionConfig:
    """Apply the pooled database path when the testsuite pool is active."""
    from providers.pooling import resolve_database_name
    from providers.scenarios import SCENARIO_MAP

    if not SCENARIO_MAP:
        return config
    scenario_name = next(iter(SCENARIO_MAP))
    pooled_db = resolve_database_name(scenario_name)
    if pooled_db:
        config = replace(config, database=pooled_db)
    return config


def _load_fb_config() -> FirebirdConnectionConfig:
    """Load config from scenario YAML, env vars, or fallback defaults."""
    config = None
    config_path = os.getenv("FIREBIRD_SCENARIOS_CONFIG_PATH")
    if config_path and os.path.exists(config_path):
        try:
            import yaml
            with open(config_path, 'r', encoding='utf-8') as f:
                data = yaml.safe_load(f)
            scenarios = (data or {}).get("scenarios") or {}
            if scenarios:
                config = FirebirdConnectionConfig(**next(iter(scenarios.values())))
        except Exception:
            config = None
    if config is None:
        default_path = os.path.join(
            os.path.dirname(__file__), "..", "..", "..", "..", "config", "firebird_scenarios.yaml"
        )
        default_path = os.path.normpath(default_path)
        if os.path.exists(default_path):
            try:
                import yaml
                with open(default_path, 'r', encoding='utf-8') as f:
                    data = yaml.safe_load(f)
                scenarios = (data or {}).get("scenarios") or {}
                if scenarios:
                    config = FirebirdConnectionConfig(**next(iter(scenarios.values())))
            except Exception:
                config = None
    if config is None:
        try:
            config = FirebirdConnectionConfig.from_env()
        except Exception:
            config = None
    if config is None:
        config = FirebirdConnectionConfig(
            host="127.0.0.1",
            port=19583,
            database="/var/lib/firebird/data/test_db",
            username="SYSDBA",
            password="password",
            charset="UTF8",
        )
    return _apply_pooled_database(config)


@pytest.fixture
def fb_config():
    return _load_fb_config()


@pytest.fixture
def fb_backend(fb_config):
    backend = FirebirdBackend(connection_config=fb_config)
    backend.connect()
    yield backend
    try:
        backend.disconnect()
    except Exception:
        pass


@pytest.fixture
def setup_test_table(fb_backend):
    table = "TEST_CRUD"
    try:
        fb_backend.execute(f'DROP TABLE {table}', fetch=False)
    except Exception:
        pass
    fb_backend.execute(f"""
        CREATE TABLE {table} (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            amount DECIMAL(18,2) DEFAULT 0,
            is_active BOOLEAN DEFAULT TRUE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    yield table
    try:
        fb_backend.execute(f'DROP TABLE {table}', fetch=False)
    except Exception:
        pass
