import pytest
from rhosocial.activerecord.backend.impl.firebird import (
    FirebirdBackend,
    FirebirdConnectionConfig,
)


@pytest.fixture
def fb_config():
    return FirebirdConnectionConfig(
        host="127.0.0.1",
        port=19583,
        database="/var/lib/firebird/data/test_db",
        username="root",
        password="password",
        charset="UTF8",
    )


@pytest.fixture
def fb_backend(fb_config):
    backend = FirebirdBackend(connection_config=fb_config)
    backend.connect()
    yield backend
    try:
        backend.disconnect()
    except Exception:
        pass


@pytest.fixture
def setup_test_table(fb_backend):
    table = "TEST_CRUD"
    try:
        fb_backend.execute(f'DROP TABLE {table}', fetch=False)
    except Exception:
        pass
    fb_backend.execute(f"""
        CREATE TABLE {table} (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            amount DECIMAL(18,2) DEFAULT 0,
            is_active BOOLEAN DEFAULT TRUE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    yield table
    try:
        fb_backend.execute(f'DROP TABLE {table}', fetch=False)
    except Exception:
        pass
