# tests/rhosocial/activerecord_firebird_test/feature/backend/test_identity_execution_confirmation.py
"""Firebird identity clauses: declared capability, executed against the server.

Firebird executes core's standard ``GENERATED {ALWAYS|BY DEFAULT} AS IDENTITY``
render unchanged from 3.0 on, so the dialect declares the probes and inherits
the core formatter rather than overriding it. This file asserts both halves:

* the probe answers, per version, including the options measured against
  the live servers (``MINVALUE`` / ``MAXVALUE`` / ``CYCLE`` / ``ORDER`` /
  ``CACHE``: all refused, both spellings of each pair);
* the rendered ``CREATE TABLE`` is accepted by the server, with a sentinel
  first so a classifier that cannot see a rejection cannot green-light
  anything.

Execution confirmation goes through the core helper
(``backend.expression.execution_testing``). The refused options are also put on
the wire through a scratch dialect that answers them ``True``, so the measured
basis of each ``False`` answer stays asserted in CI: if a future server accepts
one, that test fails and says which probe needs revisiting.
"""

import pytest

from rhosocial.activerecord.backend.dialect.exceptions import UnsupportedFeatureError
from rhosocial.activerecord.backend.expression.execution_testing import (
    ExecutionOutcome,
    classify_execution,
    confirm_expression_execution,
)
from rhosocial.activerecord.backend.expression.objects import Table
from rhosocial.activerecord.backend.expression.statements import (
    AutoIncrementClause,
    ColumnDefinition,
    CreateTableExpression,
    DropTableExpression,
    IdentityClause,
)
from rhosocial.activerecord.backend.expression.types import IntegerType
from rhosocial.activerecord.backend.impl.firebird.dialect import FirebirdDialect
from rhosocial.activerecord.base import IdentityAttribute

#: Versions on which the identity column exists. (5, 0) exercises the
#: zero-padding of two-component versions.
IDENTITY_VERSIONS = ((3, 0, 0), (5, 0), (5, 0, 4), (6, 0, 0))

#: Versions before the identity column existed.
PRE_IDENTITY_VERSIONS = ((2, 5, 0), (2, 5))

#: The three cases core's standard render must produce and the server accept:
#: bare, ALWAYS, and start/increment. The attribute is the AR-layer declaration
#: the formatter turns into an ``IdentityClause``.
IDENTITY_CASES = (
    ("bare", IdentityAttribute(), " GENERATED BY DEFAULT AS IDENTITY"),
    ("always", IdentityAttribute(generation="ALWAYS"), " GENERATED ALWAYS AS IDENTITY"),
    (
        "start_increment",
        IdentityAttribute(start=100, increment=5),
        " GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5)",
    ),
)

#: One refused option -> constructor kwargs and the feature name the refusal
#: must carry. Each two-spelling pair is listed once per spelling: both sides
#: are refused by name. ``cycle=False`` is no longer a spelling -- the negative
#: form is ``no_cycle=True``.
REFUSED_OPTIONS = (
    ("minvalue", {"minvalue": 1}, "IDENTITY MINVALUE"),
    ("maxvalue", {"maxvalue": 9999}, "IDENTITY MAXVALUE"),
    ("cycle", {"cycle": True}, "IDENTITY CYCLE"),
    ("no_cycle", {"no_cycle": True}, "IDENTITY CYCLE"),
    ("order", {"order": True}, "IDENTITY ORDER"),
    ("no_order", {"no_order": True}, "IDENTITY ORDER"),
    ("cache", {"cache": 10}, "IDENTITY CACHE"),
    ("no_cache", {"no_cache": True}, "IDENTITY CACHE"),
)


class _OptionsDeclaredDialect(FirebirdDialect):
    """The real dialect with the measured-``False`` options answered ``True``.

    Used only to render the exact clause the real probes keep off the wire, so
    the server-rejection checks test the measured basis of those ``False``
    answers rather than a hand-typed approximation of the SQL.
    """

    def supports_identity_minvalue(self) -> bool:
        return True

    def supports_identity_maxvalue(self) -> bool:
        return True

    def supports_identity_cycle(self) -> bool:
        return True

    def supports_identity_order(self) -> bool:
        return True

    def supports_identity_cache(self) -> bool:
        return True


class _AutoIncrementDeclaredDialect(FirebirdDialect):
    """The real dialect with the parameterless marker answered ``True``."""

    def supports_auto_increment_column(self) -> bool:
        return True


def _drop_table_if_present(backend, table_name: str) -> None:
    """Best-effort cleanup so a crashed run cannot poison the next one."""
    try:
        backend.execute(f'DROP TABLE "{table_name}"')
    except Exception:
        pass


def _classify_ddl(backend, table_name: str, sql: str) -> ExecutionOutcome:
    """Classify a CREATE TABLE, dropping the table first and afterwards.

    The pre-drop removes leftovers from a crashed run: without it, a second run
    would get "table already exists" -- also a rejection -- and the check could
    pass for the wrong reason. The post-drop removes the table when the server
    unexpectedly accepted the statement.
    """
    _drop_table_if_present(backend, table_name)
    try:
        return classify_execution(backend, sql)
    finally:
        _drop_table_if_present(backend, table_name)


class TestProbeDeclarations:
    """The probe answers, per version, with no server involved."""

    @pytest.mark.parametrize("version", IDENTITY_VERSIONS)
    def test_identity_declared_from_version_3_0(self, version):
        assert FirebirdDialect(version).supports_identity_column() is True

    @pytest.mark.parametrize("version", PRE_IDENTITY_VERSIONS)
    def test_identity_declined_before_version_3_0(self, version):
        assert FirebirdDialect(version).supports_identity_column() is False

    @pytest.mark.parametrize("version", IDENTITY_VERSIONS)
    def test_measured_option_probes(self, version):
        """The measured answers: start/increment/ALWAYS yes, the rest no."""
        dialect = FirebirdDialect(version)
        assert dialect.supports_identity_generation_always() is True
        assert dialect.supports_identity_start() is True
        assert dialect.supports_identity_increment() is True
        assert dialect.supports_identity_minvalue() is False
        assert dialect.supports_identity_maxvalue() is False
        assert dialect.supports_identity_cycle() is False
        assert dialect.supports_identity_order() is False
        assert dialect.supports_identity_cache() is False

    @pytest.mark.parametrize(
        "version", PRE_IDENTITY_VERSIONS + IDENTITY_VERSIONS
    )
    def test_auto_increment_marker_is_declined(self, version):
        """Firebird has no bare AUTO_INCREMENT marker, on any version."""
        assert FirebirdDialect(version).supports_auto_increment_column() is False


class TestClauseRenderingAndRefusals:
    """The standard render, and the fail-closed refusals around it."""

    def test_three_cases_render_the_standard_clause(self):
        dialect = FirebirdDialect((3, 0, 0))
        assert IdentityClause(dialect).to_sql() == (
            " GENERATED BY DEFAULT AS IDENTITY",
            (),
        )
        assert IdentityClause(dialect, "ALWAYS").to_sql() == (
            " GENERATED ALWAYS AS IDENTITY",
            (),
        )
        assert IdentityClause(dialect, start=100, increment=5).to_sql() == (
            " GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5)",
            (),
        )

    def test_identity_refused_before_version_3_0(self):
        """The mechanism gate fails closed; the clause is never rendered."""
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            IdentityClause(FirebirdDialect((2, 5, 0))).to_sql()

    @pytest.mark.parametrize(
        "case,kwargs,feature",
        REFUSED_OPTIONS,
        ids=[case for case, _, _ in REFUSED_OPTIONS],
    )
    def test_measured_false_options_are_refused_by_name(self, case, kwargs, feature):
        """A refused option raises naming it; it is never silently dropped."""
        with pytest.raises(UnsupportedFeatureError, match=feature):
            IdentityClause(FirebirdDialect((5, 0, 4)), **kwargs).to_sql()

    @pytest.mark.parametrize("version", IDENTITY_VERSIONS)
    def test_auto_increment_marker_is_refused(self, version):
        with pytest.raises(UnsupportedFeatureError, match="AUTO_INCREMENT column"):
            AutoIncrementClause(FirebirdDialect(version)).to_sql()


class TestExecutionConfirmation:
    """The rendered CREATE TABLE is executed against the live server."""

    def test_sentinels(self, fb_backend):
        """A wrong statement must be seen rejected before any acceptance counts."""
        assert (
            classify_execution(fb_backend, "THIS IS NOT SQL")
            is ExecutionOutcome.REJECTED
        )
        assert (
            classify_execution(fb_backend, "SELECT 1 FROM RDB$DATABASE")
            is ExecutionOutcome.ACCEPTED
        )

    @pytest.mark.parametrize(
        "case,attribute,clause",
        IDENTITY_CASES,
        ids=[case for case, _, _ in IDENTITY_CASES],
    )
    def test_identity_create_table_is_accepted(self, fb_backend, case, attribute, clause):
        fb_backend.introspect_and_adapt()
        dialect = fb_backend.dialect
        table = Table(dialect, f"IDENTITY_{case.upper()}")
        expression = CreateTableExpression(
            dialect,
            table,
            [
                ColumnDefinition(
                    dialect,
                    "id",
                    IntegerType(dialect),
                    attributes=[attribute],
                )
            ],
        )

        # The clause the server will be asked to parse, stated explicitly.
        sql, _ = expression.to_sql()
        assert clause.strip() in sql, sql

        outcome = confirm_expression_execution(
            fb_backend, expression, teardown=[DropTableExpression(dialect, table)]
        )
        assert outcome is ExecutionOutcome.ACCEPTED


class TestRefusedOptionsAreAlsoRejectedByTheServer:
    """The False probes rest on measurements; keep the measurements in CI.

    Each option the real dialect refuses is rendered through a scratch dialect
    and put on the wire. If a future server accepts it, the failure names the
    probe that needs revisiting instead of letting the False answer quietly
    become a capability gap.
    """

    @pytest.mark.parametrize(
        "case,kwargs,feature",
        REFUSED_OPTIONS,
        ids=[case for case, _, _ in REFUSED_OPTIONS],
    )
    def test_server_rejects_the_refused_identity_option(self, fb_backend, case, kwargs, feature):
        fb_backend.introspect_and_adapt()
        dialect = _OptionsDeclaredDialect(fb_backend.dialect.version)
        clause, _ = IdentityClause(dialect, **kwargs).to_sql()
        table_name = f"IDENTITY_REJECT_{case.upper()}"
        sql = f'CREATE TABLE "{table_name}" ("ID" INTEGER{clause})'

        assert _classify_ddl(fb_backend, table_name, sql) is ExecutionOutcome.REJECTED

    def test_server_rejects_the_auto_increment_marker(self, fb_backend):
        fb_backend.introspect_and_adapt()
        dialect = _AutoIncrementDeclaredDialect(fb_backend.dialect.version)
        marker, _ = AutoIncrementClause(dialect).to_sql()
        table_name = "IDENTITY_REJECT_AUTOINC"
        sql = f'CREATE TABLE "{table_name}" ("ID" INTEGER{marker})'

        assert _classify_ddl(fb_backend, table_name, sql) is ExecutionOutcome.REJECTED
