# tests/rhosocial/activerecord_firebird_test/feature/query/test_collation_expression.py
"""
Tests for expression-level COLLATE support on Firebird.
"""

import pytest

from rhosocial.activerecord.backend.expression import Column, Literal
from rhosocial.activerecord.backend.impl.firebird import FirebirdCollation, FirebirdDialect


@pytest.fixture
def dialect():
    return FirebirdDialect(version=(4, 0, 0))


@pytest.fixture
def collation_table(backend):
    if not getattr(backend.config, "database", None):
        pytest.skip("Firebird backend fixture has no database configured")
    with backend.context():
        backend.execute("""
            EXECUTE BLOCK AS
            BEGIN
                IF (EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'TEST_COLLATION_EXPRESSION')) THEN
                    EXECUTE STATEMENT 'DROP TABLE TEST_COLLATION_EXPRESSION';
            END
        """)
        backend.execute("""
            CREATE TABLE TEST_COLLATION_EXPRESSION (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR(100) CHARACTER SET UTF8 NOT NULL COLLATE UNICODE_CI
            )
        """)
        backend.execute("""
            INSERT INTO TEST_COLLATION_EXPRESSION (NAME)
            VALUES ('Alice')
        """)
        backend.execute("""
            INSERT INTO TEST_COLLATION_EXPRESSION (NAME)
            VALUES ('alice')
        """)
        backend.execute("""
            INSERT INTO TEST_COLLATION_EXPRESSION (NAME)
            VALUES ('Bob')
        """)
        yield "TEST_COLLATION_EXPRESSION"
        backend.execute("DROP TABLE TEST_COLLATION_EXPRESSION")


class TestFirebirdCollationExpression:
    def test_column_collate_generates_sql(self, dialect):
        expr = Column(dialect, "name", table="users").collate(FirebirdCollation.UNICODE_CI)

        sql, params = expr.to_sql()

        assert sql == '"USERS"."NAME" COLLATE UNICODE_CI'
        assert params == ()

    def test_literal_collate_preserves_parameter_binding(self, dialect):
        expr = Literal(dialect, "Alice").collate(FirebirdCollation.UNICODE_CI)

        sql, params = expr.to_sql()

        assert sql == "? COLLATE UNICODE_CI"
        assert params == ("Alice",)

    def test_rejects_schema_qualified_collation(self, dialect):
        expr = Column(dialect, "name").collate("UNICODE_CI", schema="PUBLIC")

        with pytest.raises(Exception, match="COLLATE options: schema"):
            expr.to_sql()

    def test_rejects_unsupported_collation(self, dialect):
        expr = Column(dialect, "name").collate("unknown_ci")

        with pytest.raises(ValueError, match="Unsupported Firebird collation"):
            expr.to_sql()

    def test_collate_executes_case_insensitive_match(self, backend, collation_table):
        expr = Column(backend.dialect, "NAME", table=collation_table).collate(
            FirebirdCollation.UNICODE_CI
        )
        sql, params = expr.to_sql()

        rows = backend.fetch_all(
            f"SELECT NAME FROM {collation_table} WHERE {sql} = ? ORDER BY ID",
            (*params, "Alice"),
        )

        assert [row["name"] for row in rows] == ["Alice", "alice"]
