CREATE TABLE combined_articles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content BLOB SUB_TYPE TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'draft',
    version INT DEFAULT 0,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
