# tests/rhosocial/activerecord_firebird_test/feature/backend/ddl/test_default_model_ddl.py
"""Default-type model rendering — Firebird.

``DefaultUser`` declares plain Python types with no ``UseSqlType``; Firebird
derives the column types via its own suggestion mapping. Firebird uppercases
identifiers by default.
"""

from rhosocial.activerecord.backend.impl.firebird.dialect import FirebirdDialect
from rhosocial.activerecord.examples.ddl_default_types import DefaultUser


def _render() -> str:
    sql, _ = DefaultUser.generate_create_table(dialect=FirebirdDialect()).to_sql()
    return sql


def test_default_user_has_no_explicit_sql_types():
    assert DefaultUser.__table_field_sql_types__ == {}


def test_firebird_default_user_ddl_columns():
    sql = _render()
    assert "CREATE TABLE \"DEFAULT_USERS\"" in sql
    assert '"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in sql
    assert '"USERNAME" VARCHAR(255) NOT NULL' in sql
    assert '"EMAIL" VARCHAR(255) NOT NULL' in sql
    assert '"IS_ACTIVE" BOOLEAN NOT NULL' in sql
    assert '"BALANCE" DOUBLE PRECISION NOT NULL' in sql
    assert '"CREATED_AT" TIMESTAMP NOT NULL' in sql
    assert '"METADATA" BLOB SUB_TYPE TEXT NOT NULL' in sql
    assert '"AVATAR" BLOB SUB_TYPE BINARY NOT NULL' in sql
    assert '"BIRTHDAY" DATE' in sql