# tests/rhosocial/activerecord_firebird_test/feature/backend/ddl/test_alter_table_identity.py
"""Tests for the Firebird-specific ALTER TABLE identity / column clauses.

Covers ``SET GENERATED``, ``RESTART``, ``SET INCREMENT``, ``DROP
IDENTITY`` (Firebird 3.0+) and ``POSITION`` (Firebird 4.0+) rendered
through the core ``AlterTableExpression`` dispatch. All tests are pure
construction — no database connection.
"""

import pytest

from rhosocial.activerecord.backend.dialect.exceptions import UnsupportedFeatureError
from rhosocial.activerecord.backend.expression.statements import AlterTableExpression
from rhosocial.activerecord.backend.impl.firebird.dialect import FirebirdDialect
from rhosocial.activerecord.backend.impl.firebird.expression import (
    DropIdentity,
    RestartIdentity,
    SetGenerated,
    SetIncrement,
    SetPosition,
)


def _alter(dialect, action):
    """Render a single action through the full ALTER TABLE statement."""
    return AlterTableExpression(dialect, "users", [action]).to_sql()


class TestAlterTableIdentitySQL:
    def test_set_generated_always(self):
        dialect = FirebirdDialect((3, 0, 0))
        sql, params = _alter(dialect, SetGenerated(dialect, "id", "ALWAYS"))
        assert sql == 'ALTER TABLE "USERS"  ALTER COLUMN "ID" SET GENERATED ALWAYS'
        assert params == ()

    def test_set_generated_by_default(self):
        dialect = FirebirdDialect((3, 0, 0))
        sql, params = _alter(dialect, SetGenerated(dialect, "id", "BY DEFAULT"))
        assert sql == 'ALTER TABLE "USERS"  ALTER COLUMN "ID" SET GENERATED BY DEFAULT'
        assert params == ()

    def test_restart_with_value(self):
        dialect = FirebirdDialect((3, 0, 0))
        sql, params = _alter(dialect, RestartIdentity(dialect, "id", restart_with=1000))
        assert sql == 'ALTER TABLE "USERS"  ALTER COLUMN "ID" RESTART WITH 1000'
        assert params == ()

    def test_restart_without_value(self):
        dialect = FirebirdDialect((3, 0, 0))
        sql, params = _alter(dialect, RestartIdentity(dialect, "id"))
        assert sql == 'ALTER TABLE "USERS"  ALTER COLUMN "ID" RESTART'
        assert params == ()

    def test_set_increment(self):
        dialect = FirebirdDialect((3, 0, 0))
        sql, params = _alter(dialect, SetIncrement(dialect, "id", increment=5))
        assert sql == 'ALTER TABLE "USERS"  ALTER COLUMN "ID" SET INCREMENT 5'
        assert params == ()

    def test_drop_identity(self):
        dialect = FirebirdDialect((3, 0, 0))
        sql, params = _alter(dialect, DropIdentity(dialect, "id"))
        assert sql == 'ALTER TABLE "USERS"  ALTER COLUMN "ID" DROP IDENTITY'
        assert params == ()

    def test_set_position(self):
        dialect = FirebirdDialect((4, 0, 0))
        sql, params = _alter(dialect, SetPosition(dialect, "email", position=3))
        assert sql == 'ALTER TABLE "USERS"  ALTER COLUMN "EMAIL" POSITION 3'
        assert params == ()

    def test_multiple_actions_combined(self):
        dialect = FirebirdDialect((5, 0, 0))
        expr = AlterTableExpression(
            dialect,
            "users",
            [
                SetGenerated(dialect, "id", "BY DEFAULT"),
                RestartIdentity(dialect, "id", 500),
                SetIncrement(dialect, "id", 10),
            ],
        )
        sql, params = expr.to_sql()
        assert "SET GENERATED BY DEFAULT" in sql
        assert "RESTART WITH 500" in sql
        assert "SET INCREMENT 10" in sql
        assert sql.count("ALTER COLUMN") == 3
        assert params == ()


class TestAlterTableIdentityVersionGating:
    def test_identity_actions_fb2_5_raise(self):
        dialect = FirebirdDialect((2, 5, 0))
        for action in (
            SetGenerated(dialect, "id", "ALWAYS"),
            RestartIdentity(dialect, "id"),
            SetIncrement(dialect, "id", 1),
            DropIdentity(dialect, "id"),
        ):
            with pytest.raises(UnsupportedFeatureError):
                action.to_sql()

    def test_identity_actions_fb3_ok(self):
        dialect = FirebirdDialect((3, 0, 0))
        for action in (
            SetGenerated(dialect, "id", "ALWAYS"),
            RestartIdentity(dialect, "id"),
            SetIncrement(dialect, "id", 1),
            DropIdentity(dialect, "id"),
        ):
            action.to_sql()

    def test_position_fb3_raises(self):
        dialect = FirebirdDialect((3, 0, 0))
        with pytest.raises(UnsupportedFeatureError):
            SetPosition(dialect, "email", position=3).to_sql()

    def test_position_fb4_ok(self):
        dialect = FirebirdDialect((4, 0, 0))
        sql, params = SetPosition(dialect, "email", position=3).to_sql()
        assert sql == 'ALTER COLUMN "EMAIL" POSITION 3'
        assert params == ()


class TestAlterTableActionDispatch:
    def test_actions_are_core_alter_table_actions(self):
        from rhosocial.activerecord.backend.expression.statements import AlterTableAction

        dialect = FirebirdDialect((5, 0, 0))
        for action in (
            SetGenerated(dialect, "id"),
            RestartIdentity(dialect, "id"),
            SetIncrement(dialect, "id", 1),
            DropIdentity(dialect, "id"),
            SetPosition(dialect, "email", 1),
        ):
            assert isinstance(action, AlterTableAction)

    def test_format_alter_table_statement_resolves_to_table_mixin(self):
        from rhosocial.activerecord.backend.dialect.mixins.ddl_table import TableMixin

        dialect = FirebirdDialect((5, 0, 0))
        assert type(dialect).format_alter_table_statement == TableMixin.format_alter_table_statement
