CREATE TABLE posts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content BLOB SUB_TYPE TEXT,
    published_at TIMESTAMP,
    published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
