CREATE TABLE pydantic_validated_models (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(7) NOT NULL,
    quantity INT NOT NULL,
    step_count INT NOT NULL,
    price DECIMAL(18,2) NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    status VARCHAR(10) DEFAULT 'draft',
    normalized_name VARCHAR(50) NOT NULL,
    created_token VARCHAR(255) DEFAULT 'generated-token'
)
