CREATE TABLE type_adapter_tests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    optional_name VARCHAR(255),
    optional_age INT,
    last_login TIMESTAMP
)
