CREATE TABLE type_adapter_tests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    optional_name VARCHAR(255),
    optional_age INT,
    last_login TIMESTAMP,
    is_premium BOOLEAN DEFAULT FALSE,
    unsupported_union VARCHAR(255) DEFAULT '0',
    custom_bool VARCHAR(3) DEFAULT NULL,
    optional_custom_bool VARCHAR(3) DEFAULT NULL
)
