CREATE TABLE extended_orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    order_number VARCHAR(255) NOT NULL,
    total_amount DECIMAL(18,2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'pending',
    priority VARCHAR(50) DEFAULT 'medium',
    region VARCHAR(50) DEFAULT 'default',
    category VARCHAR(255),
    product VARCHAR(255),
    department VARCHAR(255),
    year VARCHAR(10),
    quarter VARCHAR(10),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
