CREATE TABLE json_users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    age INT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    settings BLOB SUB_TYPE TEXT,
    tags BLOB SUB_TYPE TEXT,
    profile BLOB SUB_TYPE TEXT,
    roles BLOB SUB_TYPE TEXT,
    scores BLOB SUB_TYPE TEXT,
    subscription BLOB SUB_TYPE TEXT,
    preferences BLOB SUB_TYPE TEXT
)
