CREATE TABLE nodes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_id INT,
    value DECIMAL(18,2) DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
