CREATE TABLE order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INT DEFAULT 1,
    unit_price DECIMAL(18,2) NOT NULL,
    subtotal DECIMAL(18,2) DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
