CREATE TABLE posts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content BLOB SUB_TYPE TEXT,
    status VARCHAR(50) DEFAULT 'published',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
