CREATE TABLE profiles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    bio BLOB SUB_TYPE TEXT,
    avatar_url VARCHAR(500),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
