from typing import Type, Tuple, Optional, List
from rhosocial.activerecord.model import ActiveRecord, AsyncActiveRecord
from rhosocial.activerecord.backend.impl.firebird import FirebirdBackend
from rhosocial.activerecord.backend.impl.firebird.config import FirebirdConnectionConfig
from rhosocial.activerecord.connection.pool import BackendPool, AsyncBackendPool, PoolConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType
from rhosocial.activerecord.testsuite.feature.basic.connection.interfaces import IBasicConnectionProvider
from .scenarios import get_scenario, get_enabled_scenarios


class SyncTestUser(ActiveRecord):
    __table_name__ = "test_users"
    id: Optional[int] = None
    name: str
    email: str


class BasicConnectionProvider(IBasicConnectionProvider):
    def __init__(self):
        self._active_backends: List = []

    def get_test_scenarios(self) -> list:
        return list(get_enabled_scenarios().keys())

    def get_backend_class(self, scenario_name: str):
        cls, _ = get_scenario(scenario_name)
        return cls

    def get_connection_config(self, scenario_name: str):
        _, config = get_scenario(scenario_name)
        return config

    def _create_test_table(self, backend):
        try:
            backend.execute("DROP TABLE test_users", options=ExecutionOptions(stmt_type=StatementType.DDL))
        except Exception:
            pass
        backend.execute("""
            CREATE TABLE test_users (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL
            )
        """, options=ExecutionOptions(stmt_type=StatementType.DDL))

    def setup_sync_pool_and_model(self, scenario_name: str) -> Tuple[BackendPool, Type[ActiveRecord]]:
        _, config = get_scenario(scenario_name)
        pool_config = PoolConfig(
            min_size=1,
            max_size=5,
            backend_factory=lambda: FirebirdBackend(connection_config=config)
        )
        pool = BackendPool.create(pool_config)
        with pool.connection() as backend:
            self._create_test_table(backend)
            self._active_backends.append(backend)
        SyncTestUser.configure(config, FirebirdBackend)
        self._active_backends.append(SyncTestUser.__backend__)
        return pool, SyncTestUser

    def setup_sync_pool_for_crud(self, scenario_name: str) -> Tuple[BackendPool, Type[ActiveRecord]]:
        return self.setup_sync_pool_and_model(scenario_name)

    def cleanup_sync(self, scenario_name: str, pool: BackendPool):
        pool.close(timeout=1.0)
        for backend in self._active_backends:
            try:
                backend.disconnect()
            except Exception:
                pass
        self._active_backends.clear()

    async def setup_async_pool_and_model(self, scenario_name: str) -> Tuple[AsyncBackendPool, Type[AsyncActiveRecord]]:
        raise NotImplementedError("Firebird backend does not support async connection pools")

    async def setup_async_pool_for_crud(self, scenario_name: str) -> Tuple[AsyncBackendPool, Type[AsyncActiveRecord]]:
        raise NotImplementedError("Firebird backend does not support async connection pools")

    async def cleanup_async(self, scenario_name: str, pool: AsyncBackendPool):
        raise NotImplementedError("Firebird backend does not support async connection pools")
