# tests/providers/relation.py
import os
import logging
from typing import Dict, List, Tuple, Type, Set

from rhosocial.activerecord.model import ActiveRecord
from rhosocial.activerecord.testsuite.feature.relation.interfaces import (
    RelationProviderBase,
    IRelationSyncProvider,
)
from rhosocial.activerecord.testsuite.feature.relation.fixtures.models import (
    Employee,
    Department,
    Author,
    Book,
    Chapter,
    Profile,
    User,
    Post,
    Comment,
    BoundaryOwner,
    BoundaryProfile,
    BoundaryPost,
)
from .scenarios import get_enabled_scenarios, get_scenario

logger = logging.getLogger(__name__)


EMPLOYEE_DEPARTMENT_SCHEMA = """
CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description BLOB SUB_TYPE TEXT
);
CREATE TABLE employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    department_id INTEGER NOT NULL
);
DELETE FROM employees;
DELETE FROM departments;
"""

AUTHOR_BOOK_SCHEMA = """
CREATE TABLE authors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author_id INTEGER NOT NULL
);
CREATE TABLE chapters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    book_id INTEGER NOT NULL
);
CREATE TABLE profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bio BLOB SUB_TYPE TEXT NOT NULL,
    author_id INTEGER NOT NULL
);
DELETE FROM chapters;
DELETE FROM books;
DELETE FROM profiles;
DELETE FROM authors;
"""

USER_POST_COMMENT_SCHEMA = """
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    settings BLOB SUB_TYPE TEXT
);
CREATE TABLE posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body BLOB SUB_TYPE TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    view_count INTEGER NOT NULL DEFAULT 0,
    metadata BLOB SUB_TYPE TEXT
);
CREATE TABLE comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body BLOB SUB_TYPE TEXT NOT NULL,
    post_id INTEGER NOT NULL,
    meta BLOB SUB_TYPE TEXT
);
DELETE FROM comments;
DELETE FROM posts;
DELETE FROM users;
"""

RELATION_BOUNDARY_SCHEMA = """
CREATE TABLE relation_boundary_owners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE relation_boundary_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bio BLOB SUB_TYPE TEXT NOT NULL,
    owner_id INTEGER
);
CREATE TABLE relation_boundary_posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    owner_id INTEGER
);
DELETE FROM relation_boundary_posts;
DELETE FROM relation_boundary_profiles;
DELETE FROM relation_boundary_owners;
"""


class RelationProviderBaseImpl(RelationProviderBase):
    def __init__(self):
        self._created_tables: Set[str] = set()

    def get_test_scenarios(self) -> List[str]:
        return list(get_enabled_scenarios().keys())

    def _configure_with_shared_backend(self, model_class, config, backend_class, backend):
        model_class.__connection_config__ = config
        model_class.__backend_class__ = backend_class
        model_class.__backend__ = backend


class RelationSyncProvider(RelationProviderBaseImpl, IRelationSyncProvider):
    def __init__(self):
        super().__init__()
        self._active_backends: List = []
        self._sync_user_post_comment_setup = False
        self._sync_relation_boundary_setup = False

    def _execute_script(self, backend, sql: str):
        for statement in sql.split(";"):
            statement = statement.strip()
            if statement:
                backend.execute(statement)

    def _setup_employee_department(self, scenario_name):
        backend_class, config = get_scenario(scenario_name)
        Employee.configure(config, backend_class)
        backend = Employee.backend()
        backend.connect()
        backend.introspect_and_adapt()
        self._active_backends.append(backend)
        self._execute_script(backend, EMPLOYEE_DEPARTMENT_SCHEMA)
        self._configure_with_shared_backend(Department, config, backend_class, backend)
        self._created_tables.update(["employees", "departments"])
        return Employee, Department

    def _setup_author_book(self, scenario_name):
        backend_class, config = get_scenario(scenario_name)
        Author.configure(config, backend_class)
        backend = Author.backend()
        backend.connect()
        backend.introspect_and_adapt()
        self._active_backends.append(backend)
        self._execute_script(backend, AUTHOR_BOOK_SCHEMA)
        self._configure_with_shared_backend(Book, config, backend_class, backend)
        self._configure_with_shared_backend(Chapter, config, backend_class, backend)
        self._configure_with_shared_backend(Profile, config, backend_class, backend)
        self._created_tables.update(["authors", "books", "chapters", "profiles"])
        return Author, Book, Chapter, Profile

    def _setup_user_post_comment_sync(self, scenario_name):
        if not self._sync_user_post_comment_setup:
            backend_class, config = get_scenario(scenario_name)
            User.configure(config, backend_class)
            backend = User.backend()
            backend.connect()
            backend.introspect_and_adapt()
            self._active_backends.append(backend)
            self._execute_script(backend, USER_POST_COMMENT_SCHEMA)
            self._configure_with_shared_backend(Post, config, backend_class, backend)
            self._configure_with_shared_backend(Comment, config, backend_class, backend)
            self._sync_user_post_comment_setup = True
            self._created_tables.update(["users", "posts", "comments"])

    def _setup_relation_boundary_sync(self, scenario_name):
        if not self._sync_relation_boundary_setup:
            backend_class, config = get_scenario(scenario_name)
            BoundaryOwner.configure(config, backend_class)
            backend = BoundaryOwner.backend()
            backend.connect()
            backend.introspect_and_adapt()
            self._active_backends.append(backend)
            self._execute_script(backend, RELATION_BOUNDARY_SCHEMA)
            self._configure_with_shared_backend(BoundaryProfile, config, backend_class, backend)
            self._configure_with_shared_backend(BoundaryPost, config, backend_class, backend)
            self._sync_relation_boundary_setup = True
            self._created_tables.update(
                ["relation_boundary_owners", "relation_boundary_profiles", "relation_boundary_posts"]
            )

    def setup_employee_department_fixtures(
        self, scenario_name: str
    ) -> Tuple[Type[ActiveRecord], Type[ActiveRecord]]:
        return self._setup_employee_department(scenario_name)

    def setup_author_book_fixtures(
        self, scenario_name: str
    ) -> Tuple[Type[ActiveRecord], Type[ActiveRecord], Type[ActiveRecord], Type[ActiveRecord]]:
        return self._setup_author_book(scenario_name)

    def setup_user_model(self, scenario_name: str) -> Type[ActiveRecord]:
        self._setup_user_post_comment_sync(scenario_name)
        return User

    def setup_post_model(self, scenario_name: str) -> Type[ActiveRecord]:
        self._setup_user_post_comment_sync(scenario_name)
        return Post

    def setup_comment_model(self, scenario_name: str) -> Type[ActiveRecord]:
        self._setup_user_post_comment_sync(scenario_name)
        return Comment

    def setup_relation_boundary_fixtures(
        self, scenario_name: str
    ) -> Tuple[Type[ActiveRecord], Type[ActiveRecord], Type[ActiveRecord]]:
        self._setup_relation_boundary_sync(scenario_name)
        return BoundaryOwner, BoundaryProfile, BoundaryPost

    def load_relation_boundary_dataset(self, scenario_name: str, dataset_name: str) -> Dict[str, int]:
        self._setup_relation_boundary_sync(scenario_name)
        return self._load_relation_boundary_dataset(dataset_name)

    def _load_relation_boundary_dataset(self, dataset_name: str) -> Dict[str, int]:
        if dataset_name == "null_foreign_key":
            profile = BoundaryProfile(bio="No owner", owner_id=None)
            profile.save()
            return {"profile_id": profile.id}
        if dataset_name == "orphan_foreign_key":
            missing_owner_id = 999999
            post = BoundaryPost(title="Orphan post", owner_id=missing_owner_id)
            post.save()
            return {"post_id": post.id, "missing_owner_id": missing_owner_id}
        if dataset_name == "owner_without_children":
            owner = BoundaryOwner(name="Owner without children")
            owner.save()
            return {"owner_id": owner.id}
        if dataset_name == "multiple_has_one_matches":
            owner = BoundaryOwner(name="Owner with duplicate profiles")
            owner.save()
            first = BoundaryProfile(bio="First profile", owner_id=owner.id)
            first.save()
            second = BoundaryProfile(bio="Second profile", owner_id=owner.id)
            second.save()
            return {
                "owner_id": owner.id,
                "first_profile_id": first.id,
                "second_profile_id": second.id,
            }
        raise ValueError(f"Unknown relation boundary dataset: {dataset_name}")

    def _reset_sync_setup_state(self):
        self._sync_user_post_comment_setup = False
        self._sync_relation_boundary_setup = False

    def cleanup_after_test(self, scenario_name: str):
        for backend in self._active_backends:
            try:
                for table_name in list(self._created_tables):
                    try:
                        backend.execute(f"DROP TABLE {table_name}", fetch=False)
                    except Exception:
                        pass
            finally:
                try:
                    backend.disconnect()
                except Exception:
                    pass
        self._active_backends.clear()
        self._created_tables.clear()
        self._reset_sync_setup_state()
